//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Customer_Gym
    {
        public int ID_Cust { get; set; }
        public string Name_Customer { get; set; }
        public string Phone_Customer { get; set; }
        public string Carte_Dentite { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> age { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Statas { get; set; }
        public string image { get; set; }
        public Nullable<int> ID_Souscription { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        public string Type { get; set; }
        public string CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> Type_Customer { get; set; }
        public Nullable<int> Num_Days_freeze { get; set; }
        public string End_Date_freeze { get; set; }
        public Nullable<decimal> price_Sub { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Price_After_Discount { get; set; }
        public Nullable<decimal> invitation { get; set; }
        public Nullable<int> Num_Attendance { get; set; }
    }
}
