//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Detais_Data_Custmor
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cust { get; set; }
        public string Start_Date_Detais { get; set; }
        public string End_Date_Detais { get; set; }
        public Nullable<int> Num_Day_Attendance { get; set; }
        public string Remarks_Detais { get; set; }
        public Nullable<decimal> Longueur_Detais { get; set; }
        public Nullable<decimal> le_Poids_Detais { get; set; }
        public Nullable<decimal> Muscles_P_C { get; set; }
        public Nullable<decimal> Fats_P_C { get; set; }
        public Nullable<decimal> perfect_weight { get; set; }
    }
}
