//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Type_Souscription
    {
        public int ID_Souscription { get; set; }
        public string Type_Sub { get; set; }
        public Nullable<int> Num_Day { get; set; }
        public Nullable<decimal> price_Sub { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Price_After_Discount { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> invitation { get; set; }
    }
}
