//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitation
    {
        public int ID_invitation { get; set; }
        public Nullable<int> ID_Cust { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Carte_Dentite { get; set; }
        public Nullable<int> age { get; set; }
        public string Tr_Data { get; set; }
        public string Remarks { get; set; }
    }
}
