//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ__Attendance
    {
        public Nullable<int> ID_Souscription { get; set; }
        public int ID { get; set; }
        public Nullable<int> ID_Cust { get; set; }
        public Nullable<int> ID_Code_USER { get; set; }
        public string Tr_Date { get; set; }
        public string Time_in { get; set; }
        public string Time_out { get; set; }
        public Nullable<int> Num_Day_Attendance { get; set; }
        public Nullable<bool> ready { get; set; }
        public Nullable<int> Num_Day { get; set; }
        public string Name_Customer { get; set; }
        public string Phone_Customer { get; set; }
        public string Type { get; set; }
        public Nullable<int> Type_Customer { get; set; }
        public Nullable<int> Num_Attendance { get; set; }
        public Nullable<decimal> invitation { get; set; }
        public Nullable<decimal> Price_After_Discount { get; set; }
        public Nullable<decimal> price_Sub { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Type_Sub { get; set; }
    }
}
